### ISSUE TITLE
No Releases ?

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/tci-webintegrator#1]
There aren't any public releases to install the studio SDK ..

https://github.com/TIBCOSoftware/tci-webintegrator/releases/download/<version>/wi-studio.tar.gz

**Comment by retgits** [comment]
Hi! We noticed a small error so we had to change the zips. The [releases](https://github.com/TIBCOSoftware/tci-webintegrator/releases/tag/1.0.0) are back again now
