### ISSUE TITLE
Wiki - URL for fork of wiki

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/tci-webintegrator#2]
The documented link:

https://github.com/TIBCOSoftware/tci.wiki.git

either isn't public or isn't valid.  There are numerous typo's that i'd like to fix and i'd like to augment the getting started doc to help someone as ignorant as i am to get up to speed.

**Comment by retgits** [comment]
Ah! Thanks for catching that one. The correct URL should have been https://github.com/TIBCOSoftware/tci-webintegrator.wiki.git (reflecting the repo name). As you're making updates please submit a pull request so one of the admins can review it.

**Comment by ayh20** [comment]
That link doesn't work either ....


------ Original Message ------

**Comment by retgits** [comment]
Hi! Where do you see that link? The readme points to https://github.com/TIBCOSoftware/tci-webintegrator/wiki (which is the correct link), to clone and edit it you should use 
```
git clone https://github.com/TIBCOSoftware/tci-webintegrator.wiki.git
```

**Comment by ayh20** [comment]
On the bottom of the wiki page is says:

Fork it and send a pull request.

that's what you get when you click it ....  but looking at it again, i 
have no idea why it's a clickable link.

The clone link [on the right] is correct  (same as your clone command)

------ Original Message ------
