### ISSUE TITLE
Activity Json Title field and special chars

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/tci-webintegrator#3]
Hi ... i discovered that  problems are caused if you have a backslash in a title it has strange results when you use the activity.

if you have:
"title": "Black\White List IP Checker",

When you add the activity to a flow, the default name for the tile is "Black\WhiteListIPChecker" at runtime.

if you run the flow with the default name you will see that the system doesn't interpret the activties correctly.

![image](https://user-images.githubusercontent.com/17643158/30586166-fc1e10fa-9d26-11e7-8afa-27ea42eaa100.png)

Renaming the tile, fixes the problem.   Setting the title in the activity.json to not include the special char also fixes the problem by not adding the title with an invalid name.

**Comment by retgits** [comment]
Thanks for sharing Andy! I'll make sure that we update the documentation with the correct information.

**Comment by retgits** [comment]
In the latest update of the code we've added some validation guidelines as well. Please see https://tibcosoftware.github.io/tci-webintegrator/extensions/organizing-code/activity-json/
