### ISSUE TITLE
Tooling scripts invalid & invalid curl URL's

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/tci-webintegrator#4]
Running the npn run sdk command throws the following error. (Windows)

PS D:\Data\Documents\GithubClones\tci-webintegrator\tooling> npm run sdk

> wi-cli@1.0.0 sdk D:\Data\Documents\GithubClones\tci-webintegrator\tooling
> ./scripts/wi-studio.sdk.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wi-cli@1.0.0 sdk: `./scripts/wi-studio.sdk.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wi-cli@1.0.0 sdk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ahampshi\AppData\Roaming\npm-cache\_logs\2017-10-10T13_26_39_909Z-debug.log

Also the script contains references to http://llbuild2.na.tibco.com:8080/guestAuth/repository/download/Atmosphere_Tci_Wi_WiStudioApi/.lastSuccessful/wi-studio.tar.gz?branch=master  which is a intenal TIBCO server.

**Comment by pdhar-tibco** [comment]
Hi Andy,
You can now use wi-cli which works with Web Integrator Studio SDK 1.1.0 . Going forward the wi-cli will use the latest SDK from github automatically.

**Comment by ayh20** [comment]
This hasn't fixed anything i can see the error is exactly the same
PS D:\Data\Documents\GoWorkSpace\src\github.com\TIBCOSoftware\tci-webintegrator\tooling> npm run sdk

> wi-cli@1.0.0 sdk D:\Data\Documents\GoWorkSpace\src\github.com\TIBCOSoftware\tci-webintegrator\tooling
> ./scripts/wi-cli.sdk.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wi-cli@1.0.0 sdk: `./scripts/wi-cli.sdk.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wi-cli@1.0.0 sdk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ahampshi\AppData\Roaming\npm-cache\_logs\2017-10-16T09_00_40_536Z-debug.log

debug log attached
[2017-10-16T09_00_40_536Z-debug.log](https://github.com/TIBCOSoftware/tci-webintegrator/files/1386806/2017-10-16T09_00_40_536Z-debug.log)
