### ISSUE TITLE
Tooling scripts invalid 

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/tci-webintegrator#5]
New issue as i can't reopen a closed issue in github.

Fixes to #4 haven't changed anything it's still fails in exactly the same way as it did. I may have confused the issue with reporting the download location problem but that's not the problem i needed fixed.

Repo has been clean cloned onto a Win10 machine. Instructions in the tooling directory say:

After checking out this project run npm run sdk -- Which will get the sdk dependencies required by the cli

Result:

PS D:\Data\Documents\GoWorkSpace\src\github.com\TIBCOSoftware\tci-webintegrator\tooling> npm run sdk

> wi-cli@1.0.0 sdk D:\Data\Documents\GoWorkSpace\src\github.com\TIBCOSoftware\tci-webintegrator\tooling
> ./scripts/wi-cli.sdk.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wi-cli@1.0.0 sdk: `./scripts/wi-cli.sdk.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wi-cli@1.0.0 sdk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ahampshi\AppData\Roaming\npm-cache\_logs\2017-10-16T09_00_40_536Z-debug.log

Log

[2017-10-16T09_00_40_536Z-debug.log](https://github.com/TIBCOSoftware/tci-webintegrator/files/1386829/2017-10-16T09_00_40_536Z-debug.log)

**Comment by retgits** [comment]
Hi Andy, please note that the sdk is only required if you want to test your typescript contributions without uploading them to TIBCO Cloud Integration. In the meantime we have been working hard on the different tools surrounding TCI and a new CLI to help create extensions has been added as well. Please check out https://github.com/TIBCOSoftware/tci-webintegrator/tree/master/tools and let us know if you have any issues
