### ISSUE TITLE
can't send HTML emails with ootb Activity

### ISSUE THREAD

**Issue by JGrotex** [TIBCOSoftware/tci-webintegrator#8]
see details here:
https://community.tibco.com/questions/tci-web-integrator-ootb-sendmail-activity-send-html-emails

**Comment by retgits** [comment]
Hi Jorg, the Web Integrator runtime indeed uses the smtp package to enable email capability and that doesn't support HTML based emails. I'm closing the issue here on GitHub as this isn't an issue with the SDK we provide or the docs for it. We'll take it into consideration for new releases though.
